---
- name: '{{ ansible_name_module }} | file | Create Directories' 
  file:
    mode: '0644'
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ dir_secrets }}/runner/etc/ansible-runner-service/certs/client'
    - '{{ dir_secrets }}/runner/etc/ansible-runner-service/certs/server'
    - '{{ dir_platform }}/runner/etc/ansible-runner-service'
    - '{{ dir_platform }}/runner/usr/share/ansible-runner-service/env'
    - '{{ dir_platform }}/runner/usr/share/ansible-runner-service/project'
    - '{{ dir_platform }}/runner/usr/share/ansible-runner-service/inventory'
    - '{{ dir_platform }}/runner/usr/share/ansible-runner-service/artifacts'
